-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS public.measurements
(
    id bigserial,
    measured_on timestamp without time zone NOT NULL,
    station bigserial,
    air_attribute bigserial,
    value numeric,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.stations
(
    id bigserial,
    name character varying NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT unique_stationsname UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.air_attributes
(
    id bigserial,
    name character varying NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT unique_air_attribute_name UNIQUE (name)
);

ALTER TABLE IF EXISTS public.measurements
    ADD FOREIGN KEY (air_attribute)
    REFERENCES public.air_attributes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.measurements
    ADD FOREIGN KEY (station)
    REFERENCES public.stations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;